services:
  web:
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_NAME=lime
      - DB_HOST=localhost
      - DB_USER=${LIME_DB_USER}
      - DB_PASSWD=${LIME_DB_PASSWD}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
